### ISSUE TITLE
git repository destroyed

### ISSUE THREAD

**Issue by jallmer** [joergen7/consensus-prediction#10]
1) git clone
2) berks 
3) chef
4) git pull (not a git repository)
It seems that the process 2-3 somehow destroys the local git repository.

**Comment by joergen7** [comment]
You have to cd back to the consensus-prediction folder before doing git pull.

**Comment by jallmer** [comment]
Sure, did that.

**Comment by joergen7** [comment]
So just to be sure, what you entered was something like

```
mkdir cookbooks
cd cookbooks
git clone https://github.com/joergen7/consensus-prediction.git
cd consensus-prediction
berks vendor ..
cd ../..
chef-client -z -r "consensus-prediction::_common,consensus-prediction::default"
cd cookbooks/consensus-prediction
git pull
```

and then it broke.

**Comment by jallmer** [comment]
Yes, somewhere during that sequence of events the git repository broke (.git dir is missing).

**Comment by joergen7** [comment]
I am trying to reproduce it in the above way ... it may take a while.

**Comment by joergen7** [comment]
berks vendor indeed screws the git rep.

**Comment by joergen7** [comment]
Alternatively, you could git clone the cookbooks chef-bioinf-worker and chef-cuneiform yourself. You would have to make sure to perform a git pull on each of the three prior to calling chef-client. But then you do not need to berks vendor anymore.
