### ISSUE TITLE
Properly place barleyprots.fa and spectra.tar

### ISSUE THREAD

**Issue by joergen7** [joergen7/consensus-prediction#13]
Can I properly include the two files into the Chef cookbook?

Doing this will make sure, the files are placed properly in installation scenarios other than chef-zero.

The files will be placed into /opt/data. Calling Cuneiform with -w /opt/data will make them acessible in Cuneiform as is. In Cuneiform you can then write something like

```
spectra-tar = 'spectra.tar';
fa = 'barleyprots.fa';
```

**Comment by jallmer** [comment]
You may place them, but be aware that they only represent test data and are not very meaningful.

**Comment by joergen7** [comment]
If you use them in the workflow, they are meaningful enough. Feel free to come up with more meaningful data later on.
