### ISSUE TITLE
MSGFPlusAdapter

### ISSUE THREAD

**Issue by jallmer** [joergen7/consensus-prediction#14]
The MSGFPlusAdapter is not available on the path.
http://ftp.mi.fu-berlin.de/pub/OpenMS/documentation/html/TOPP_MSGFPlusAdapter.html

**Comment by joergen7** [comment]
I get it, that this tool is not part of the MSGF distribution? On the above web page, I have not found a download link.

**Comment by jallmer** [comment]
This tool should be part of the TOPP tools in openms.

**Comment by joergen7** [comment]
Ok, I found it. But this tool is available. It has been included together with FileConverter.

**Comment by jallmer** [comment]
Hmm, when I type MSGFPlusAdapter on the console it is not available :(

**Comment by jallmer** [comment]
Just rebuild everything and fasta_pro.exe is working, but no MSGFPlusAdapter.

**Comment by joergen7** [comment]
Works on my side. No idea, what's the problem here. Can we have a Skype screen sharing session about this issue?

**Comment by joergen7** [comment]
What is the output of

```
echo $PATH
```

btw?

**Comment by jallmer** [comment]
Hi Jörgen,

hier die Ausgabe:
jens@jensvb:~/Downloads$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games

Gruss,
Jens

2015-10-14 18:29 GMT+03:00 Jörgen Brandt notifications@github.com:

**Comment by jallmer** [comment]
Klar, können wir wieder machen.

2015-10-14 18:15 GMT+03:00 Jörgen Brandt notifications@github.com:
