### ISSUE TITLE
fasta_pro.exe

### ISSUE THREAD

**Issue by jallmer** [joergen7/consensus-prediction#15]
tandem.exe is on the path, but the file fasta_pro.exe (in the same folder) is not.
It is needed to index the database for running tandem.exe.

**Comment by jallmer** [comment]
The command fasta_pro.exe barleyprots.fa
should create a barleyprots.pro file but fails to do.

**Comment by joergen7** [comment]
2 Questions:
- How do I get the file barleyprots.pro?
- If you mean barleyprots.fa instead, the fasta_pro.exe doc tells me
  
  USAGE: tandem filename
  where filename is any valid path to an XML input file.

Hence, nothing but an xml file will do the job here.

PS: For the future, can you append the error messages you get, when things fail?

**Comment by jallmer** [comment]
fasta_pro.exe sollte eigentlich eine fasta Datei in eine pro Datei
umwandeln.
Der Vorgang ist trivial: fasta_pro.exe /path/to/file.fasta dann kommt die
Datei file.fasta.pro als Ergebnis heraus.
Die fasta_pro die ich dir geschickt habe macht das anstandslos auf meinem
Laptop.
Leider gibt deine fasta_pro.exe die genau gleiche Fehlermeldung (xml datei)
wie auch die tandem.exe (dabei ist das aber schon in Ordnung ... die
braucht eine XML Datei als Eingabe).
Kann es irgendwie passiert sein, dass du die tandem.exe gebaut hast und die
fasta_pro.exe genannt hast?

Gruss,
Jens

2015-10-14 18:22 GMT+03:00 Jörgen Brandt notifications@github.com:

**Comment by joergen7** [comment]
You are right of course. Now the only thing left to do is, find out how to build fasta_pro.exe.
