### ISSUE TITLE
MSGFPlusAdapter

### ISSUE THREAD

**Issue by jallmer** [joergen7/consensus-prediction#16]
MSGFPlusAdapter needs location of the jar file.
Can a sym link to the msgf jar file be added to local/bin ?

**Comment by joergen7** [comment]
Not exactly how you ordered it, but you can now do something like this:

```
MSGFPlusAdapter `whereis MSGFPlus.jar`
```

The same, btw, works with `whereis mods.xml` and `whereis usermods.xml`.
