### ISSUE TITLE
Remove mods.xml, usermods.xml

### ISSUE THREAD

**Issue by jallmer** [joergen7/consensus-prediction#17]
The deftask for omssa can now accept the files as input.
If the deftask below is acceptable, you can remove the files above.

deftask runOmssa(OmssaRes(File):mzMLFile(File) db_blastDB_tar(File) blast_index_name omssa_mods(File) omssa_usermods(File)) in bash _{
    tar xf $db_blastDB_tar
    ol=`whereis omssacl`
    arr=($ol)
    ln -s ${arr[1]} omssacl
    OMSSAAdapter -in $mzMLFile -out res.idXML -database ${blast_index_name}.psq -omssa_executable omssacl
    OmssaRes=res.idXML
}_

**Comment by joergen7** [comment]
I have removed the mods.xml and usermods.xml from the OMSSA installation script. I'm afraid, they won't delete themselves in your current installation, which is why I would ask you to delete them. You will find them in /usr/local/etc.
