### ISSUE TITLE
chef scripts broken?

### ISSUE THREAD

**Issue by jallmer** [joergen7/consensus-prediction#18]
jens@jensvb:~$ sudo chef-client -z -r "consensus-prediction::_common,consensus-prediction::default"
[sudo] password for jens: 
[2015-10-15T12:44:31+03:00] WARN: No config file found or specified on command line, using command line options.
Starting Chef Client, version 12.4.4
resolving cookbooks for run list: ["consensus-prediction::_common", "consensus-prediction::default"]
Synchronizing Cookbooks:
- consensus-prediction
- chef-cuneiform
- chef-bioinf-worker
  Compiling Cookbooks...
  Converging 82 resources
  Recipe: consensus-prediction::_common
- bash[apt-get_update] action run
  - execute "bash"  "/tmp/chef-script20151015-5576-i9ackv"
    Recipe: chef-bioinf-worker::openms
- apt_package[cmake] action install (up to date)
- apt_package[autoconf] action install (up to date)
- apt_package[g++] action install (up to date)
- apt_package[qt4-dev-tools] action install (up to date)
- apt_package[patch] action install (up to date)
- apt_package[libtool] action install (up to date)
- apt_package[git] action install (up to date)
- apt_package[libboost-regex-dev] action install (up to date)
- apt_package[libboost-iostreams-dev] action install (up to date)
- apt_package[libboost-date-time-dev] action install (up to date)
- apt_package[libboost-math-dev] action install (up to date)
- apt_package[libsvm-dev] action install (up to date)
- apt_package[libglpk-dev] action install (up to date)
- apt_package[libzip-dev] action install (up to date)
- apt_package[libxerces-c-dev] action install (up to date)
- apt_package[libbz2-dev] action install (up to date)
- apt_package[libeigen3-dev] action install (up to date)
- directory[/opt/software] action create (up to date)
- directory[/opt/software/OpenMS] action create (up to date)
- directory[/opt/software/OpenMS/OpenMS-build] action create (up to date)
- directory[/opt/software/OpenMS/contrib-build] action create (up to date)
- git[git_clone_openms_src] action checkout (up to date)
- git[git_clone_openms_contrib] action checkout (up to date)
- bash[build_openms_contrib_seqan] action run (skipped due to not_if)
- bash[build_openms_contrib_wildmagic] action run (skipped due to not_if)
- bash[configure_openms] action run (skipped due to not_if)
- bash[build_openms] action run (skipped due to not_if)
- bash[update_environment] action run (skipped due to not_if)
- bash[update_path] action run (skipped due to not_if)
  Recipe: chef-bioinf-worker::java
- apt_package[openjdk-7-jdk] action install (up to date)
  Recipe: chef-bioinf-worker::msgf
- directory[/opt/software] action create (up to date)
- directory[/opt/archive] action create (up to date)
- apt_package[unzip] action install (up to date)
- remote_file[/opt/archive/MSGFPlus.zip] action create_if_missing (up to date)
- bash[extract_msgf] action run (skipped due to not_if)
- file[/usr/local/bin/msgf] action create (up to date)
- file[/usr/local/bin/buildsa] action create (up to date)
- link[/usr/local/etc/MSGFPlus.jar] action create
  
  Error executing action `create` on resource 'link[/usr/local/etc/MSGFPlus.jar]'
    ================================================================================
  
    Errno::ENOENT
  ---
  
    No such file or directory @ sys_fail2 - (/opt/software/msgf/MSGFPlus.jar, /usr/local/etc/MSGFPlus.jar)
  
    Resource Declaration:
  ---
  
    # In /home/jens/.chef/local-mode-cache/cache/cookbooks/chef-bioinf-worker/recipes/msgf.rb
  
     47: link "#{node.dir.etc}/MSGFPlus.jar" do
     48:   to msgf_jar
     49: end
  
    Compiled Resource:
  ---
  
    # Declared in /home/jens/.chef/local-mode-cache/cache/cookbooks/chef-bioinf-worker/recipes/msgf.rb:47:in `from_file'
  
    link("/usr/local/etc/MSGFPlus.jar") do
      action [:create]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      to "/opt/software/msgf/MSGFPlus.jar"
      link_type :symbolic
      target_file "/usr/local/etc/MSGFPlus.jar"
      declared_type :link
      cookbook_name "chef-bioinf-worker"
      recipe_name "msgf"
    end

Running handlers:
[2015-10-15T12:44:45+03:00] ERROR: Running exception handlers
Running handlers complete
[2015-10-15T12:44:45+03:00] ERROR: Exception handlers complete
Chef Client failed. 1 resources updated in 14.170393111 seconds
[2015-10-15T12:44:45+03:00] FATAL: Stacktrace dumped to /home/jens/.chef/local-mode-cache/cache/chef-stacktrace.out
[2015-10-15T12:44:45+03:00] ERROR: link[/usr/local/etc/MSGFPlus.jar](chef-bioinf-worker::msgf line 47) had an error: Errno::ENOENT: No such file or directory @ sys_fail2 - (/opt/software/msgf/MSGFPlus.jar, /usr/local/etc/MSGFPlus.jar)
[2015-10-15T12:44:47+03:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by joergen7** [comment]
Has MSGF been installed properly? What is the content of /opt/software/msgf?

**Comment by jallmer** [comment]
> /opt/software/msgf$ ls
> LICENSE.txt  Mods.txt  MSGFPlus.jar  README.txt

**Comment by joergen7** [comment]
This should really work. Can we skype about it?
