### ISSUE TITLE
OpenMS

### ISSUE THREAD

**Issue by jallmer** [joergen7/consensus-prediction#19]
It seems like that there might be two versions of OpenMS co-installed so that some TOPP tools are from different versions .. how can we check that?

**Comment by jallmer** [comment]
This seems to be version 1.11.1 of OpenMS.
Maybe we should use version 2.0
http://sourceforge.net/projects/open-ms/files/OpenMS/OpenMS-2.0/

**Comment by joergen7** [comment]
vagrant@default-ubuntu-1404:/opt/software/OpenMS/OpenMS-build/bin$ OpenMSInfo 

# OpenMS Version:

Version      : 2.0.0
Build time   : Oct 17 2015, 10:44:47
Git sha1     : 4776889
Git branch   : deploy

# Installation information:

Data path    : /opt/software/OpenMS/OpenMS-src/share/OpenMS
Temp path    : /tmp
Userdata path: /home/vagrant/

# Build information:

Source path  : /opt/software/OpenMS/OpenMS-src/src/openms
Binary path  : /opt/software/OpenMS/OpenMS-build/src/openms

# OS Information:

Name: Linux
Version: unkown
Architecture: unkown
