### ISSUE TITLE
TOPP

### ISSUE THREAD

**Issue by jallmer** [joergen7/consensus-prediction#20]
I made a clean install (Ubuntu 15) and started the workflow.
Unfortunately, TOPP is not accessible (i.e.: tools like FileConverter, adapters are not on the path.).

If I perform sudo apt-get install TOPP, I believe it leads to problems since the TOPP version available via sudo seems to be outdated.

**Comment by joergen7** [comment]
I take it, that you rebooted so that the path gets updated in the shell. Can we have a Skype session about it, because on my side this works perfectly.
