### ISSUE TITLE
remove crux

### ISSUE THREAD

**Issue by jallmer** [joergen7/consensus-prediction#7]
There are some issues with crux and a different program should be used instead.

**Comment by joergen7** [comment]
The bug seems to be reproducible only sporadically. Sometimes the svn checkout seems to fail (it's a big resource). So far, I could not figure out, whether Chef releases the svn lock properly after a failed try. Only if it does, retrying makes sense (which is enabled by default).

**Comment by joergen7** [comment]
I'll add MSGF too, but crux needs to run. (Eventually MSGF needs to be checked out too.)

**Comment by joergen7** [comment]
It is as I expected. Chef does not clean up the svn repository after failure. That's why retrying is useless. Fixing is under way.
